### ISSUE TITLE
7080 SFF 声卡驱动不正常

### ISSUE THREAD

**Issue by janfon0715** [Dynamix1997/Hackintosh-Dell-OptiPlex-7080-Series#1]
系统报告中音频设备列表为空

**Comment by Dynamix1997** [comment]
IORegistryExplorer保存个文档发我吧
![image](https://user-images.githubusercontent.com/53791111/102027972-b1cf7b00-3de2-11eb-9450-3b0eb8d94809.png)

**Comment by janfon0715** [comment]
[hotwind的iMac.ioreg.zip](https://github.com/Dynamix1997/Hackintosh-Dell-OptiPlex-7080-Series/files/5703874/hotwind.iMac.ioreg.zip)
由于7080不是主力机，不是天天用，所以现在才发

**Comment by janfon0715** [comment]
另外补充一句 https://github.com/3dudu/dell-optiplex-7080-hackintosh-opencore 这个我也尝试过，最新版本的主机音频是OK的。

**Comment by Dynamix1997** [comment]
![A33AB93C-96AE-41ED-A0EA-79E465473AA9](https://user-images.githubusercontent.com/53791111/102423583-543a6900-4044-11eb-86d6-c8fd6542ca1b.png)
你注入的ID是 11。我仿冒的ALC256 ID是 67 

![F74A4A75-F2CE-4CA5-8683-CD6748BF7A35](https://user-images.githubusercontent.com/53791111/102423667-82b84400-4044-11eb-97ee-64afbcd1dbd8.png) 
67  （Unicode("C")）

**Comment by janfon0715** [comment]
💯
