### ISSUE TITLE
关机问题

### ISSUE THREAD

**Issue by tdlllllllll** [Dynamix1997/Hackintosh-Dell-OptiPlex-7080-Series#1]
哈喽，你的可以正常关机吗？我的mt用了你的之后，其他都很正常，但是关机一直不断电。

**Comment by Dynamix1997** [comment]
我的没问题呀

**Comment by Dynamix1997** [comment]
用其他的EFI能正常关机嘛 或者详细描述一下无法关机的状态， 是系统关机动画一直转 还是 黑屏之后主机不断电 ？

**Comment by tdlllllllll** [comment]
黑屏之后不断电，只能是强制重启那种。有可能是我bios设置的问题？PS：最近不在家，可能星期五再回复你。

**Comment by Dynamix1997** [comment]
是使用我这个EFI出现的情况还是？一直都有？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tdlllllllll <notifications@github.com&gt;
发送时间: 2021年1月27日 13:25
收件人: Dynamix1997/Hackintosh-Dell-OptiPlex-7080-Series <Hackintosh-Dell-OptiPlex-7080-Series@noreply.github.com&gt;
抄送: Dynamix1997 <3106142068@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[Dynamix1997/Hackintosh-Dell-OptiPlex-7080-Series] 关机问题 (#1)





 
黑屏之后不断电，只能是强制重启那种。有可能是我bios设置的问题？PS：最近不在家，可能星期五再回复你。

**Comment by tdlllllllll** [comment]
一直都有。
你的配置是i5的对吧，我的是i7的，不知道是不是i7版本的通病

**Comment by Dynamix1997** [comment]
嗯呢我的是 i5
