### ISSUE TITLE
ALC 256

### ISSUE THREAD

**Issue by abdllhcrk** [Dynamix1997/Hackintosh-Dell-OptiPlex-7080-Series#2]
Hello, I am using Acer Swift 3. It also uses ALC256 for sound. But although I tried all layouts, output works but internal mic never works.  I think the problem is related to Intel Smart Sound Technology if I am not wrong. Can you help me to add New codec support for ALC256 ? I tried everything but i really don't know what to do. If you want, I can send my Codec Dump file.

**Comment by Dynamix1997** [comment]
![31D15525-2714-4357-AF58-02819C799458](https://user-images.githubusercontent.com/53791111/103160953-30caa780-4816-11eb-90e0-8e57c1f54612.png)
Yes, the built-in microphone of Intel smart audio doesn't work in hackintosh

**Comment by abdllhcrk** [comment]
So there is no hope for my internal mic, right ?

**Comment by Dynamix1997** [comment]
✅
