### ISSUE TITLE
老大，叨扰，问两个问题

### ISSUE THREAD

**Issue by JiangLennon** [Dynamix1997/Hackintosh-Dell-OptiPlex-7080-Series#2]
1，你用的OpenCore什么版本？我下了最新的OC65，487,212字节。你的是499,712字节。
2，ACPI目录里基本上没东西，https://opencore.slowgeek.com/检查你的plist说得放点USBX之类的东西。

**Comment by Dynamix1997** [comment]
请仔细阅读 README.md 如有其他有价值的疑问🤔️或问题请提出
